<!DOCTYPE html>
<html lang="en">

<head>
    <title>Page Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="styles.css">
</head>
<body>

<?php include 'nav.php'; ?>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.php">Αρχική</a></li>
    <li class="breadcrumb-item active" aria-current="page">Συχνές Ερωτήσεις</li>
  </ol>
</nav>

<center><h1>Συχνές Ερωτήσεις</h1> </center> 

<tr>
<td valign="top">
<p>&nbsp;</p>
<p><strong>1. &Pi;&omega;&sigmaf; &mu;&pi;&omicron;&rho;ώ &nu;&alpha; &gamma;ί&nu;&omega; &mu;έ&lambda;&omicron;&sigmaf; &tau;&eta;&sigmaf; &Epsilon;.&Omicron;.&Delta;.;</strong></p>
<p>&Gamma;&iota;&alpha; &nu;&alpha; &gamma;ί&nu;&epsilon;&iota; &kappa;ά&pi;&omicron;&iota;&omicron;&sigmaf; &mu;έ&lambda;&omicron;&sigmaf; &tau;&eta;&sigmaf; &Epsilon;.&Omicron;.&Delta;. &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &pi;&alpha;&rho;&alpha;&kappa;&omicron;&lambda;&omicron;&upsilon;&theta;ή&sigma;&epsilon;&iota; &kappa;&alpha;&iota; &nu;&alpha; &alpha;&pi;&omicron;&phi;&omicron;&iota;&tau;ή&sigma;&epsilon;&iota; &epsilon;&pi;&iota;&tau;&upsilon;&chi;ώ&sigmaf; &alpha;&pi;ό &tau;&eta; &sigma;&chi;&omicron;&lambda;ή &beta;&alpha;&sigma;&iota;&kappa;ή&sigmaf; &epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;&eta;&sigmaf; &nu;έ&omega;&nu; &mu;&epsilon;&lambda;ώ&nu;, &eta; &omicron;&pi;&omicron;ί&alpha; &delta;&iota;&epsilon;&xi;ά&gamma;&epsilon;&tau;&alpha;&iota; &sigma;&upsilon;&nu;ή&theta;&omega;&sigmaf; 1 &phi;&omicron;&rho;ά &tau;&omicron; &chi;&rho;ό&nu;&omicron;, &mu;ό&lambda;&iota;&sigmaf; &sigma;&upsilon;&gamma;&kappa;&epsilon;&nu;&tau;&rho;&omega;&theta;&epsilon;ί &iota;&kappa;&alpha;&nu;ό&sigmaf; &alpha;&rho;&iota;&theta;&mu;ό&sigmaf; &upsilon;&pi;&omicron;&psi;&eta;&phi;ί&omega;&nu;.</p>
<p>&nbsp;</p>
<p><strong>2. &Gamma;&iota;&alpha; &nu;&alpha; &gamma;ί&nu;&epsilon;&iota; &kappa;&alpha;&nu;&epsilon;ί&sigmaf; &mu;έ&lambda;&omicron;&sigmaf;, &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; έ&chi;&epsilon;&iota; &iota;&delta;&iota;&alpha;ί&tau;&epsilon;&rho;&epsilon;&sigmaf; &sigma;&omega;&mu;&alpha;&tau;&iota;&kappa;έ&sigmaf; &iota;&kappa;&alpha;&nu;ό&tau;&eta;&tau;&epsilon;&sigmaf;;</strong></p>
<p>Ό&chi;&iota;! &Delta;&epsilon;&nu; &alpha;&pi;&alpha;&iota;&tau;&omicron;ύ&nu;&tau;&alpha;&iota; &iota;&delta;&iota;&alpha;ί&tau;&epsilon;&rho;&epsilon;&sigmaf; &sigma;&omega;&mu;&alpha;&tau;&iota;&kappa;έ&sigmaf; &iota;&kappa;&alpha;&nu;ό&tau;&eta;&tau;&epsilon;&sigmaf;, &pi;&rho;έ&pi;&epsilon;&iota; ό&mu;&omega;&sigmaf; &nu;&alpha; έ&chi;&epsilon;&iota; &mu;&iota;&alpha; &tau;&upsilon;&pi;&iota;&kappa;ά &kappa;&alpha;&lambda;ή &phi;&upsilon;&sigma;&iota;&kappa;ή &kappa;&alpha;&tau;ά&sigma;&tau;&alpha;&sigma;&eta; &kappa;&alpha;&iota; &kappa;&upsilon;&rho;ί&omega;&sigmaf; &kappa;&alpha;&lambda;ή &upsilon;&gamma;&epsilon;ί&alpha;.</p>
<p>&nbsp;</p>
<p><strong>3. &Pi;&omicron;&iota;&alpha; &eta; &epsilon;&xi;έ&lambda;&iota;&xi;&eta; &epsilon;&nu;ό&sigmaf; &mu;έ&lambda;&omicron;&upsilon;&sigmaf; &mu;&epsilon;&tau;ά &tau;&eta;&nu; &omicron;&lambda;&omicron;&kappa;&lambda;ή&rho;&omega;&sigma;&eta; &tau;&eta;&sigmaf; &beta;&alpha;&sigma;&iota;&kappa;ή&sigmaf; &epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;&eta;&sigmaf;;</strong></p>
<p>&Mu;ό&lambda;&iota;&sigmaf; &alpha;&pi;&omicron;&phi;&omicron;&iota;&tau;ή&sigma;&epsilon;&iota; &kappa;ά&pi;&omicron;&iota;&omicron;&sigmaf; &alpha;&pi;ό &tau;&omicron; &sigma;&chi;&omicron;&lambda;&epsilon;ί&omicron; &beta;&alpha;&sigma;&iota;&kappa;ή&sigmaf; &epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;&eta;&sigmaf; &epsilon;&pi;&iota;&lambda;έ&gamma;&epsilon;&iota; &sigma;&epsilon; &pi;&omicron;&iota;&omicron; &alpha;&pi;ό &tau;&alpha; &tau;&mu;ή&mu;&alpha;&tau;&alpha; &delta;&rho;ά&sigma;&eta;&sigmaf; &theta;έ&lambda;&epsilon;&iota; &nu;&alpha; &epsilon;&nu;&tau;&alpha;&chi;&theta;&epsilon;ί. &Mu;έ&sigma;&omega; &tau;&omicron;&upsilon; &tau;&mu;ή&mu;&alpha;&tau;&omicron;&sigmaf; &theta;&alpha; &sigma;&upsilon;&nu;&epsilon;&chi;ί&sigma;&epsilon;&iota; &tau;&eta;&nu; &epsilon;&xi;&epsilon;&iota;&delta;&iota;&kappa;&epsilon;&upsilon;&mu;έ&nu;&eta; &epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;ή &tau;&omicron;&upsilon;, &beta;ά&sigma;&eta; &tau;&omicron;&upsilon; &epsilon;&kappa;&pi;&alpha;&iota;&delta;&epsilon;&upsilon;&tau;&iota;&kappa;&omicron;ύ &pi;&rho;&omicron;&gamma;&rho;ά&mu;&mu;&alpha;&tau;&omicron;&sigmaf;. &Mu;&epsilon; &tau;&eta;&nu; &omicron;&lambda;&omicron;&kappa;&lambda;ή&rho;&omega;&sigma;&eta; &tau;&eta;&sigmaf; &beta;&alpha;&sigma;&iota;&kappa;ή&sigmaf; &sigma;&chi;&omicron;&lambda;ή&sigmaf; &tau;&omicron; &nu;έ&omicron; &mu;έ&lambda;&omicron;&sigmaf; &gamma;ί&nu;&epsilon;&tau;&alpha;&iota; &laquo;&delta;ό&kappa;&iota;&mu;&omicron;&raquo; &kappa;&alpha;&iota; &mu;&epsilon;&tau;ά &alpha;&pi;ό 18 &mu;ή&nu;&epsilon;&sigmaf; έ&chi;&epsilon;&iota; &tau;&omicron; &delta;&iota;&kappa;&alpha;ί&omega;&mu;&alpha; &nu;&alpha; &kappa;&alpha;&tau;&alpha;&theta;έ&sigma;&epsilon;&iota; &alpha;ί&tau;&eta;&sigma;&eta; &tau;&alpha;&kappa;&tau;&iota;&kappa;&omicron;ύ &mu;έ&lambda;&omicron;&upsilon;&sigmaf; &tau;&eta;&nu; &omicron;&pi;&omicron;ί&alpha; &epsilon;&gamma;&kappa;&rho;ί&nu;&epsilon;&iota; &eta; &Gamma;&epsilon;&nu;&iota;&kappa;ή &Sigma;&upsilon;&nu;έ&lambda;&epsilon;&upsilon;&sigma;&eta; &kappa;&alpha;&tau;ό&pi;&iota;&nu; &epsilon;&iota;&sigma;&eta;&gamma;ή&sigma;&epsilon;&omega;&nu; &tau;&omicron;&upsilon; &Delta;.&Sigma;. &kappa;&alpha;&iota; &tau;&omicron;&upsilon; &tau;&mu;&eta;&mu;&alpha;&tau;ά&rho;&chi;&eta; &tau;&omicron;&upsilon;.</p>
<p>&nbsp;</p>
<p><strong>4. &Alpha;&nu; &lambda;ό&gamma;&omega; &epsilon;&pi;&alpha;&gamma;&gamma;&epsilon;&lambda;&mu;&alpha;&tau;&iota;&kappa;ώ&nu; ή ά&lambda;&lambda;&omega;&nu; &upsilon;&pi;&omicron;&chi;&rho;&epsilon;ώ&sigma;&epsilon;&omega;&nu; &delta;&epsilon;&nu; &mu;&pi;&omicron;&rho;ώ &nu;&alpha; &sigma;&upsilon;&mu;&mu;&epsilon;&tau;ά&sigma;&chi;&omega; &sigma;&epsilon; &kappa;ά&pi;&omicron;&iota;&alpha; &epsilon;&pi;&iota;&chi;&epsilon;ί&rho;&eta;&sigma;&eta; έ&chi;&omega; &kappa;ά&pi;&omicron;&iota;&epsilon;&sigmaf; &kappa;&upsilon;&rho;ώ&sigma;&epsilon;&iota;&sigmaf;;</strong></p>
<p>&Alpha;&pi;&omicron;&lambda;ύ&tau;&omega;&sigmaf; &kappa;&alpha;&mu;ί&alpha;, &alpha;&rho;&kappa;&epsilon;ί &tau;&omicron; &mu;έ&lambda;&omicron;&sigmaf; &nu;&alpha; &pi;&alpha;&rho;&omicron;&upsilon;&sigma;&iota;ά&zeta;&epsilon;&iota; &mu;&iota;&alpha; &sigma;&chi;&epsilon;&tau;&iota;&kappa;ή &delta;&rho;ά&sigma;&eta; &kappa;&alpha;&tau;ά &tau;&eta; &delta;&iota;ά&rho;&kappa;&epsilon;&iota;&alpha; &tau;&omicron;&upsilon; έ&tau;&omicron;&upsilon;&sigmaf;. &Omicron;&iota; &upsilon;&pi;&omicron;&chi;&rho;&epsilon;ώ&sigma;&epsilon;&iota;&sigmaf; &tau;&eta;&sigmaf; &Epsilon;.&Omicron;.&Delta;. &epsilon;ί&nu;&alpha;&iota; &alpha;&upsilon;&xi;&eta;&mu;έ&nu;&epsilon;&sigmaf; &kappa;&alpha;&iota; &gamma;&iota;&alpha; &tau;&omicron; &lambda;ό&gamma;&omicron; &alpha;&upsilon;&tau;ό &kappa;ά&theta;&epsilon; &beta;&omicron;ή&theta;&epsilon;&iota;&alpha; &epsilon;ί&nu;&alpha;&iota; &epsilon;&pi;&iota;&theta;&upsilon;&mu;&eta;&tau;ή.</p>
<p>&nbsp;</p>
<p><strong>5. &Epsilon;ί&mu;&alpha;&iota; &mu;&iota;&alpha;&sigmaf; &kappa;ά&pi;&omicron;&iota;&alpha;&sigmaf; &eta;&lambda;&iota;&kappa;ί&alpha;&sigmaf; ή &omicron;&iota; &sigma;&omega;&mu;&alpha;&tau;&iota;&kappa;έ&sigmaf; &mu;&omicron;&upsilon; &iota;&kappa;&alpha;&nu;ό&tau;&eta;&tau;&epsilon;&sigmaf; &delta;&epsilon;&nu; &mu;&omicron;&upsilon; &epsilon;&pi;&iota;&tau;&rho;έ&pi;&omicron;&upsilon;&nu; &nu;&alpha; &epsilon;&mu;&pi;&lambda;&alpha;&kappa;ώ &epsilon;&nu;&epsilon;&rho;&gamma;ά &sigma;&epsilon; &epsilon;&pi;&iota;&chi;&epsilon;&iota;&rho;ή&sigma;&epsilon;&iota;&sigmaf;. &Pi;&omega;&sigmaf; &mu;&pi;&omicron;&rho;ώ &alpha;&lambda;&lambda;&iota;ώ&sigmaf; &nu;&alpha; &beta;&omicron;&eta;&theta;ή&sigma;&omega;;</strong></p>
<p>&Upsilon;&pi;ά&rho;&chi;&omicron;&upsilon;&nu; &epsilon;&rho;&gamma;&alpha;&sigma;ί&epsilon;&sigmaf; &gamma;&iota;&alpha; ό&lambda;&omicron;&upsilon;&sigmaf;. &Eta; &upsilon;&pi;&omicron;&sigma;&tau;ή&rho;&iota;&xi;&eta; &epsilon;&pi;&iota;&chi;&epsilon;&iota;&rho;ή&sigma;&epsilon;&omega;&nu; &epsilon;ί&nu;&alpha;&iota; &alpha;&kappa;&rho;&omicron;&gamma;&omega;&nu;&iota;&alpha;ί&omicron;&sigmaf; &lambda;ί&theta;&omicron;&sigmaf; &sigma;&tau;&eta;&nu; &omicron;&mu;&alpha;&lambda;ή &kappa;&alpha;&iota; &theta;&epsilon;&tau;&iota;&kappa;ή έ&kappa;&beta;&alpha;&sigma;&eta; &tau;&eta;&sigmaf; &kappa;&alpha;&iota; &alpha;&pi;&alpha;&iota;&tau;&omicron;ύ&nu;&tau;&alpha;&iota; &pi;&omicron;&lambda;&lambda;ά ά&tau;&omicron;&mu;&alpha;. &Epsilon;&pi;&iota;&pi;&lambda;έ&omicron;&nu; &sigma;&epsilon; ά&lambda;&lambda;&epsilon;&sigmaf; &delta;&rho;ά&sigma;&epsilon;&iota;&sigmaf; &eta; &sigma;&upsilon;&mu;&beta;&omicron;&lambda;ή ό&lambda;&omega;&nu; &epsilon;ί&nu;&alpha;&iota; &alpha;&nu;&alpha;&gamma;&kappa;&alpha;ί&alpha;. &Eta; &Epsilon;.&Omicron;.&Delta;. &delta;&epsilon;&nu; &epsilon;ί&nu;&alpha;&iota; &mu;ό&nu;&omicron; &omicron;&iota; 5 ή &omicron;&iota; 10 &pi;&omicron;&upsilon; &epsilon;&pi;&iota;&chi;&epsilon;&iota;&rho;&omicron;ύ&nu; &sigma;&epsilon; &mu;&iota;&alpha; &delta;&iota;ά&sigma;&omega;&sigma;&eta;. &Epsilon;ί&nu;&alpha;&iota; έ&nu;&alpha;&sigmaf; &mu;&eta;&chi;&alpha;&nu;&iota;&sigma;&mu;ό&sigmaf; &pi;&omicron;&upsilon; &alpha;&pi;&omicron;&tau;&epsilon;&lambda;&epsilon;ί&tau;&alpha;&iota; &alpha;&pi;ό &pi;&omicron;&lambda;&lambda;ά ά&tau;&omicron;&mu;&alpha; &pi;&omicron;&upsilon; &tau;&omicron; &kappa;&alpha;&theta;έ&nu;&alpha; &alpha;&pi;ό &tau;&omicron; &pi;ό&sigma;&tau;&omicron; &tau;&omicron;&upsilon; &sigma;&upsilon;&mu;&beta;ά&lambda;&lambda;&epsilon;&iota; &gamma;&iota;&alpha; &tau;&omicron;&nu; &kappa;&omicron;&iota;&nu;ό &sigma;&kappa;&omicron;&pi;ό.</p>
<p>&nbsp;</p>
<p><strong>6. &Omicron;&iota; &epsilon;&theta;&epsilon;&lambda;&omicron;&nu;&tau;έ&sigmaf; &tau;&eta;&sigmaf; &Epsilon;&Omicron;&Delta; &pi;&lambda;&eta;&rho;ώ&nu;&omicron;&nu;&tau;&alpha;&iota; &gamma;&iota;&alpha; &tau;&iota;&sigmaf; &upsilon;&pi;&eta;&rho;&epsilon;&sigma;ί&epsilon;&sigmaf; &tau;&omicron;&upsilon;&sigmaf;;</strong></p>
<p>&Phi;&upsilon;&sigma;&iota;&kappa;ά &kappa;&alpha;&iota; ό&chi;&iota;!</p>
<p>&nbsp;</p>
<p><strong>7. &Epsilon;ί&mu;&alpha;&iota; &alpha;&nu;ή&lambda;&iota;&kappa;&omicron;&sigmaf;/&eta;, &mu;&pi;&omicron;&rho;ώ &nu;&alpha; &sigma;&upsilon;&mu;&mu;&epsilon;&tau;ά&sigma;&chi;&omega; &epsilon;&nu;&epsilon;&rho;&gamma;ά &sigma;&tau;&eta;&nu; &Epsilon;.&Omicron;.&Delta;.;</strong></p>
<p>&Gamma;&iota;&alpha; &tau;&alpha; &alpha;&nu;ή&lambda;&iota;&kappa;&alpha; &upsilon;&pi;&omicron;&psi;ή&phi;&iota;&alpha; &mu;έ&lambda;&eta; &alpha;&pi;&alpha;&iota;&tau;&epsilon;ί&tau;&alpha;&iota; &eta; έ&gamma;&gamma;&rho;&alpha;&phi;&eta; &sigma;&upsilon;&gamma;&kappa;&alpha;&tau;ά&theta;&epsilon;&sigma;&eta; &tau;&omicron;&upsilon; &kappa;&eta;&delta;&epsilon;&mu;ό&nu;&alpha; &tau;&omicron;&upsilon;&sigmaf;, &tau;&eta;&nu; &omicron;&pi;&omicron;ί&alpha; &pi;&rho;&omicron;&sigma;&kappa;&omicron;&mu;ί&zeta;&epsilon;&iota; &omicron; ί&delta;&iota;&omicron;&sigmaf; (&kappa;&eta;&delta;&epsilon;&mu;ό&nu;&alpha;&sigmaf;) &sigma;&tau;&alpha; &gamma;&rho;&alpha;&phi;&epsilon;ί&alpha; &tau;&eta;&sigmaf; &Epsilon;.&Omicron;.&Delta;. &mu;&alpha;&zeta;ί &mu;&epsilon; &tau;&eta;&nu; &alpha;ί&tau;&eta;&sigma;&eta; &epsilon;&gamma;&gamma;&rho;&alpha;&phi;ή&sigmaf; &sigma;&tau;&eta; &sigma;&chi;&omicron;&lambda;ή.</p>
<p>&nbsp;</p>
<p><strong>8. &Sigma;&epsilon; &pi;&omicron;&iota;&epsilon;&sigmaf; &pi;&epsilon;&rho;&iota;&pi;&tau;ώ&sigma;&epsilon;&iota;&sigmaf; &epsilon;&nu;&epsilon;&rho;&gamma;&omicron;&pi;&omicron;&iota;&epsilon;ί&tau;&alpha;&iota; &eta; &Epsilon;&Omicron;&Delta;;</strong></p>
<p>&Eta; &Epsilon;.&Omicron;.&Delta;. &epsilon;&nu;&epsilon;&rho;&gamma;&omicron;&pi;&omicron;&iota;&epsilon;ί&tau;&alpha;&iota; &alpha;&pi;ό &tau;&omicron;&upsilon;&sigmaf; &epsilon;&pi;ί&sigma;&eta;&mu;&omicron;&upsilon;&sigmaf; &kappa;&rho;&alpha;&tau;&iota;&kappa;&omicron;ύ&sigmaf; &phi;&omicron;&rho;&epsilon;ί&sigmaf; - &Pi;&omicron;&lambda;&iota;&tau;&iota;&kappa;ή &Pi;&rho;&omicron;&sigma;&tau;&alpha;&sigma;ί&alpha;, &Pi;&upsilon;&rho;&omicron;&sigma;&beta;&epsilon;&sigma;&tau;&iota;&kappa;ή &Upsilon;&pi;&eta;&rho;&epsilon;&sigma;ί&alpha;, &Epsilon;&lambda;&lambda;&eta;&nu;&iota;&kappa;ή &Alpha;&sigma;&tau;&upsilon;&nu;&omicron;&mu;ί&alpha;, &Lambda;&iota;&mu;&epsilon;&nu;&iota;&kappa;ό &Sigma;ώ&mu;&alpha; - &pi;&rho;&omicron;&kappa;&epsilon;&iota;&mu;έ&nu;&omicron;&upsilon; &nu;&alpha; &beta;&omicron;&eta;&theta;ή&sigma;&epsilon;&iota; &kappa;&alpha;&iota; &nu;&alpha; &upsilon;&pi;&omicron;&sigma;&tau;&eta;&rho;ί&xi;&epsilon;&iota; &omicron;&rho;&gamma;&alpha;&nu;&omega;&mu;έ&nu;&alpha; &kappa;&alpha;&iota; &epsilon;&xi;&epsilon;&iota;&delta;&iota;&kappa;&epsilon;&upsilon;&mu;έ&nu;&alpha; &sigma;&tau;&iota;&sigmaf; &pi;&epsilon;&rho;&iota;&pi;&tau;ώ&sigma;&epsilon;&iota;&sigmaf;:</p>
<p>&bull;&Kappa;&alpha;&tau;&alpha;&sigma;&tau;ά&sigma;&epsilon;&iota;&sigmaf; έ&kappa;&tau;&alpha;&kappa;&tau;&eta;&sigmaf; &alpha;&nu;ά&gamma;&kappa;&eta;&sigmaf; &kappa;&alpha;&iota; &mu;&alpha;&zeta;&iota;&kappa;ώ&nu; &kappa;&alpha;&tau;&alpha;&sigma;&tau;&rho;&omicron;&phi;ώ&nu;.</p>
<p>&bull;Έ&rho;&epsilon;&upsilon;&nu;&alpha; &amp; &delta;&iota;ά&sigma;&omega;&sigma;&eta; &sigma;&tau;&omicron; &omicron;&rho;&epsilon;&iota;&nu;ό &pi;&epsilon;&delta;ί&omicron;.</p>
<p>&bull;Έ&rho;&epsilon;&upsilon;&nu;&alpha; &amp; &delta;&iota;ά&sigma;&omega;&sigma;&eta; &sigma;&tau;&omicron; &upsilon;&gamma;&rho;ό &sigma;&tau;&omicron;&iota;&chi;&epsilon;ί&omicron; (&theta;ά&lambda;&alpha;&sigma;&sigma;&alpha;, &pi;&omicron;&tau;ά&mu;&iota;&alpha;, &lambda;ί&mu;&nu;&epsilon;&sigmaf;).</p>
<p>&bull;&Pi;&alpha;&rho;&omicron;&chi;ή &alpha;&nu;&theta;&rho;&omega;&pi;&iota;&sigma;&tau;&iota;&kappa;ή&sigmaf; &beta;&omicron;ή&theta;&epsilon;&iota;&alpha;&sigmaf; &sigma;&tau;&eta;&nu; &Epsilon;&lambda;&lambda;ά&delta;&alpha; &kappa;&alpha;&iota; &sigma;&tau;&omicron; &epsilon;&xi;&omega;&tau;&epsilon;&rho;&iota;&kappa;ό.</p>
<p>&nbsp;</p>
<p><strong>9. &Delta;&epsilon;&nu; &mu;&pi;&omicron;&rho;ώ &nu;&alpha; &sigma;&upsilon;&mu;&mu;&epsilon;&tau;έ&chi;&omega; &sigma;&epsilon; &epsilon;&pi;&iota;&chi;&epsilon;&iota;&rho;ή&sigma;&epsilon;&iota;&sigmaf; έ&rho;&epsilon;&upsilon;&nu;&alpha;&sigmaf; &delta;&iota;ά&sigma;&omega;&sigma;&eta;&sigmaf;. &Mu;&pi;&omicron;&rho;ώ &nu;&alpha; &gamma;ί&nu;&omega; &mu;έ&lambda;&omicron;&sigmaf; &tau;&eta;&sigmaf; &Epsilon;&Omicron;&Delta; &kappa;&alpha;&iota; &nu;&alpha; &upsilon;&pi;&omicron;&sigma;&tau;&eta;&rho;ί&zeta;&omega; &mu;&epsilon; ά&lambda;&lambda;&omicron;&nu; &tau;&rho;ό&pi;&omicron; &tau;&eta;&nu; &omicron;&rho;&gamma;ά&nu;&omega;&sigma;&eta;;</strong></p>
<p>&Mu;&pi;&omicron;&rho;&epsilon;ί&sigmaf; &nu;&alpha; &gamma;ί&nu;&epsilon;&iota;&sigmaf; &laquo;&epsilon;&xi;&omega;&tau;&epsilon;&rho;&iota;&kappa;ό&sigmaf; &sigma;&upsilon;&nu;&epsilon;&rho;&gamma;ά&tau;&eta;&sigmaf;&raquo; ή &laquo;&upsilon;&pi;&omicron;&sigma;&tau;&eta;&rho;&iota;&kappa;&tau;ή&sigmaf;&raquo; &kappa;&alpha;&iota; &nu;&alpha; &epsilon;&nu;&tau;&alpha;&chi;&theta;&epsilon;ί&sigmaf; έ&tau;&sigma;&iota; &sigma;&tau;&eta;&nu; &omicron;&iota;&kappa;&omicron;&gamma;έ&nu;&epsilon;&iota;&alpha; &tau;&eta;&sigmaf; &Epsilon;.&Omicron;.&Delta;. &Sigma;&omicron;&upsilon; &pi;&alpha;&rho;έ&chi;&epsilon;&tau;&alpha;&iota; &alpha;&nu;&tau;ί&sigma;&tau;&omicron;&iota;&chi;&eta; &tau;&alpha;&upsilon;&tau;ό&tau;&eta;&tau;&alpha; &kappa;&alpha;&iota; &epsilon;&nu;&eta;&mu;&epsilon;&rho;ώ&nu;&epsilon;&sigma;&alpha;&iota; &gamma;&iota;&alpha; ό&lambda;&epsilon;&sigmaf; &tau;&iota;&sigmaf; &delta;&rho;ά&sigma;&eta;&sigmaf; &tau;&eta;&sigmaf;.</p>
<p>&nbsp;</p>
<p><strong>10. &Pi;ό&sigma;&omicron; &delta;&iota;&alpha;&rho;&kappa;&epsilon;ί &eta; &beta;&alpha;&sigma;&iota;&kappa;ή &epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;&eta;;</strong></p>
<p>&Eta; &Sigma;&chi;&omicron;&lambda;ή &Beta;&alpha;&sigma;&iota;&kappa;ή&sigmaf; &Epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;&eta;&sigmaf; &delta;&iota;&epsilon;&xi;ά&gamma;&epsilon;&tau;&alpha;&iota; &kappa;&alpha;&iota; &pi;&epsilon;&rho;&alpha;&iota;ώ&nu;&epsilon;&tau;&alpha;&iota; &sigma;&epsilon; &chi;&rho;&omicron;&nu;&iota;&kappa;ό &delta;&iota;ά&sigma;&tau;&eta;&mu;&alpha; &alpha;&nu;ά&lambda;&omicron;&gamma;&omicron; &mu;&epsilon; &tau;&eta;&nu; &pi;&alpha;&rho;&alpha;&kappa;&omicron;&lambda;&omicron;ύ&theta;&eta;&sigma;&eta; &tau;&omicron;&upsilon; &pi;&rho;&omicron;&gamma;&rho;ά&mu;&mu;&alpha;&tau;&omicron;&sigmaf; &tau;&omega;&nu; &mu;&alpha;&theta;&eta;&mu;ά&tau;&omega;&nu;.</p>
<p>&nbsp;</p>
<p><strong>11. &Pi;&omicron;&iota;&epsilon;&sigmaf; &epsilon;ί&nu;&alpha;&iota; &omicron;&iota; &upsilon;&pi;&omicron;&chi;&rho;&epsilon;ώ&sigma;&epsilon;&iota;&sigmaf; &mu;&omicron;&upsilon; &omega;&sigmaf; &mu;έ&lambda;&omicron;&sigmaf; &tau;&eta;&sigmaf; &omicron;&rho;&gamma;ά&nu;&omega;&sigma;&eta;&sigmaf;;</strong></p>
<p>&Kappa;ά&theta;&epsilon; &mu;έ&lambda;&omicron;&sigmaf; &tau;&eta;&sigmaf; &Epsilon;.&Omicron;.&Delta;. &omicron;&phi;&epsilon;ί&lambda;&epsilon;&iota; &nu;&alpha; &pi;&lambda;&eta;&rho;ώ&nu;&epsilon;&iota; &tau;&eta;&nu; &epsilon;&tau;ή&sigma;&iota;&alpha; &sigma;&upsilon;&nu;&delta;&rho;&omicron;&mu;ή &tau;&omicron;&upsilon; &pi;&omicron;&upsilon; &epsilon;ί&nu;&alpha;&iota; 60 &epsilon;&upsilon;&rho;ώ. &Pi;έ&rho;&alpha;&nu; &alpha;&upsilon;&tau;ώ&nu; &tau;&omicron; &kappa;ά&theta;&epsilon; &mu;έ&lambda;&omicron;&sigmaf; &theta;&alpha; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &pi;&alpha;&rho;&omicron;&upsilon;&sigma;&iota;ά&zeta;&epsilon;&iota; &mu;&iota;&alpha; &epsilon;&lambda;ά&chi;&iota;&sigma;&tau;&eta; &delta;&rho;ά&sigma;&eta; &sigma;&epsilon; &epsilon;&pi;&iota;&chi;&epsilon;&iota;&rho;ή&sigma;&epsilon;&iota;&sigmaf; &kappa;&alpha;&iota; &upsilon;&pi;&omicron;&sigma;&tau;ή&rho;&iota;&xi;&eta;&sigmaf; &delta;&iota;&alpha;&phi;ό&rho;&omega;&nu; &delta;&iota;&omicron;&rho;&gamma;&alpha;&nu;ώ&sigma;&epsilon;&omega;&nu; ό&pi;&omega;&sigmaf; &pi;.&chi;. &sigma;&upsilon;&nu;έ&delta;&rho;&iota;&alpha;, &kappa;ά&lambda;&upsilon;&psi;&eta; &pi;&omicron;&lambda;&iota;&tau;&iota;&sigma;&tau;&iota;&kappa;ώ&nu; ή &alpha;&theta;&lambda;&eta;&tau;&iota;&kappa;ώ&nu; &epsilon;&kappa;&delta;&eta;&lambda;ώ&sigma;&epsilon;&omega;&nu; &kappa;.&alpha;. &Delta;&epsilon;&nu; &epsilon;ί&nu;&alpha;&iota; &upsilon;&pi;&omicron;&chi;&rho;&epsilon;&omega;&tau;&iota;&kappa;ή &eta; &pi;&alpha;&rho;&omicron;&upsilon;&sigma;ί&alpha; &sigma;&epsilon; ό&lambda;&epsilon;&sigmaf;, &alpha;&lambda;&lambda;ά &omicron;ύ&tau;&epsilon; &kappa;&alpha;&iota; &eta; &pi;&lambda;ή&rho;&eta;&sigmaf; &alpha;&pi;&omicron;&upsilon;&sigma;ί&alpha;.</p>
<p>&nbsp;</p>
<p><strong>12. &Chi;&rho;&epsilon;&iota;ά&zeta;&omicron;&mu;&alpha;&iota; &delta;&iota;&kappa;ό &mu;&omicron;&upsilon; &epsilon;&xi;&omicron;&pi;&lambda;&iota;&sigma;&mu;ό;</strong></p>
<p>&Eta; &Epsilon;.&Omicron;.&Delta;. &delta;&iota;&alpha;&theta;έ&tau;&epsilon;&iota; &tau;&epsilon;&chi;&nu;&iota;&kappa;ό &omicron;&mu;&alpha;&delta;&iota;&kappa;ό &epsilon;&xi;&omicron;&pi;&lambda;&iota;&sigma;&mu;ό (&alpha;&sigma;&upsilon;&rho;&mu;ά&tau;&omicron;&upsilon;&sigmaf;, &sigma;&chi;&omicron;&iota;&nu;&iota;ά, &phi;&omicron;&rho;&epsilon;ί&alpha;, &kappa;&lambda;&pi;) &pi;&omicron;&upsilon; &alpha;&xi;&iota;&omicron;&pi;&omicron;&iota;&epsilon;ί&tau;&alpha;&iota; &sigma;&epsilon; &epsilon;&kappa;&pi;&alpha;&iota;&delta;&epsilon;ύ&sigma;&epsilon;&iota;&sigmaf;, &alpha;&sigma;&kappa;ή&sigma;&epsilon;&iota;&sigmaf; &kappa;&alpha;&iota; &pi;&epsilon;&rho;&iota;&sigma;&tau;&alpha;&tau;&iota;&kappa;ά, ό&mu;&omega;&sigmaf; &tau;&alpha; &mu;έ&lambda;&eta; &tau;&eta;&sigmaf; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &delta;&iota;&alpha;&theta;έ&tau;&omicron;&upsilon;&nu; &kappa;&alpha;&iota; &tau;&omicron;&nu; &alpha;&tau;&omicron;&mu;&iota;&kappa;ό &epsilon;&xi;&omicron;&pi;&lambda;&iota;&sigma;&mu;ό &tau;&omicron;&upsilon;&sigmaf;, &pi;&omicron;&upsilon; &alpha;&pi;&omicron;&tau;&epsilon;&lambda;&epsilon;ί&tau;&alpha;&iota; &kappa;&upsilon;&rho;ί&omega;&sigmaf; &alpha;&pi;ό &mu;&eta; &delta;&alpha;&nu;&epsilon;&iota;&zeta;ό&mu;&epsilon;&nu;&alpha; &epsilon;ί&delta;&eta; έ&nu;&delta;&upsilon;&sigma;&eta;&sigmaf; &amp; &delta;&iota;&alpha;&beta;ί&omega;&sigma;&eta;&sigmaf; (&pi;.&chi;. ά&rho;&beta;&upsilon;&lambda;&alpha;, &upsilon;&pi;&nu;ό&sigma;&alpha;&kappa;&omicron; &kappa;&lambda;&pi;). &Alpha;&sigma;&phi;&alpha;&lambda;ώ&sigmaf; &epsilon;ί&nu;&alpha;&iota; &iota;&delta;&iota;&alpha;ί&tau;&epsilon;&rho;&alpha; &chi;&rho;ή&sigma;&iota;&mu;&omicron; &alpha;&nu; &kappa;ά&pi;&omicron;&iota;&omicron;&sigmaf; &delta;&iota;&alpha;&theta;έ&tau;&epsilon;&iota; &alpha;&tau;&omicron;&mu;&iota;&kappa;ό &tau;&epsilon;&chi;&nu;&iota;&kappa;ό &epsilon;&xi;&omicron;&pi;&lambda;&iota;&sigma;&mu;ό (&pi;.&chi;. &kappa;&rho;ά&nu;&omicron;&sigmaf;, &zeta;ώ&nu;&eta; &alpha;&nu;&alpha;&rho;&rho;ί&chi;&eta;&sigma;&eta;&sigmaf; &kappa;&lambda;&pi;) &chi;&omega;&rho;ί&sigmaf; ό&mu;&omega;&sigmaf; &nu;&alpha; &alpha;&pi;&omicron;&tau;&epsilon;&lambda;&epsilon;ί &beta;&alpha;&sigma;&iota;&kappa;ή &pi;&rho;&omicron;ϋ&pi;ό&theta;&epsilon;&sigma;&eta;.</p>
<p>&nbsp;</p>
<p><strong>13. &Alpha;&nu; &pi;&epsilon;&rho;ά&sigma;&omega; &tau;&omicron; &sigma;&chi;&omicron;&lambda;&epsilon;ί&omicron; &tau;&eta;&sigmaf; &Epsilon;&Omicron;&Delta; &pi;&alpha;ί&rho;&nu;&omega; &mu;ό&rho;&iota;&alpha; &gamma;&iota;&alpha; &tau;&eta;&nu; &pi;&rho;ό&sigma;&lambda;&eta;&psi;ή &mu;&omicron;&upsilon; &sigma;&epsilon; &kappa;ά&pi;&omicron;&iota;&alpha; &delta;&eta;&mu;ό&sigma;&iota;&alpha; &upsilon;&pi;&eta;&rho;&epsilon;&sigma;ί&alpha;;</strong></p>
<p>Ό&chi;&iota; &kappa;&alpha;&iota; &sigma;ί&gamma;&omicron;&upsilon;&rho;&alpha; &delta;&epsilon;&nu; &delta;&eta;&mu;&iota;&omicron;&upsilon;&rho;&gamma;ή&theta;&eta;&kappa;&epsilon; &gamma;&iota;&alpha; &alpha;&upsilon;&tau;ό&nu; &tau;&omicron; &sigma;&kappa;&omicron;&pi;ό &eta; &Epsilon;.&Omicron;.&Delta;.</p>
<p>&nbsp;</p>
<p><strong>14. &Pi;&omega;&sigmaf; &kappa;&alpha;&iota; &alpha;&pi;ό &pi;&omicron;&iota;&omicron;&upsilon;&sigmaf; &chi;&rho;&eta;&mu;&alpha;&tau;&omicron;&delta;&omicron;&tau;&epsilon;ί&tau;&alpha;&iota; &eta; &Epsilon;.&Omicron;.&Delta;;</strong></p>
<p>&Eta; &lambda;&epsilon;&iota;&tau;&omicron;&upsilon;&rho;&gamma;ί&alpha; &tau;&eta;&sigmaf; &Epsilon;.&Omicron;.&Delta;. &sigma;&tau;&eta;&rho;ί&zeta;&epsilon;&tau;&alpha;&iota; &sigma;&tau;&omicron; &mu;&epsilon;&gamma;&alpha;&lambda;ύ&tau;&epsilon;&rho;&omicron; &pi;&omicron;&sigma;&omicron;&sigma;&tau;ό &tau;&eta;&sigmaf;, &sigma;&tau;&eta;&nu; &epsilon;&upsilon;&alpha;&iota;&sigma;&theta;&eta;&tau;&omicron;&pi;&omicron;ί&eta;&sigma;&eta; &tau;&omega;&nu; &iota;&delta;&iota;&omega;&tau;ώ&nu;. &Epsilon;&tau;&alpha;&iota;&rho;ί&epsilon;&sigmaf; ή &mu;&epsilon;&mu;&omicron;&nu;&omega;&mu;έ&nu;&alpha; &phi;&upsilon;&sigma;&iota;&kappa;ά &pi;&rho;ό&sigma;&omega;&pi;&alpha; &sigma;&tau;&eta;&rho;ί&zeta;&omicron;&upsilon;&nu; &mu;&epsilon; &delta;&omega;&rho;&epsilon;έ&sigmaf; &tau;&eta;&nu; &omicron;&rho;&gamma;ά&nu;&omega;&sigma;&eta;. &Epsilon;&pi;ί&sigma;&eta;&sigmaf; &eta; &pi;ώ&lambda;&eta;&sigma;&eta; &eta;&mu;&epsilon;&rho;&omicron;&lambda;&omicron;&gamma;ί&omega;&nu; &kappa;&alpha;&iota; &omicron;&iota; &sigma;&upsilon;&nu;&delta;&rho;&omicron;&mu;έ&sigmaf; &tau;&omega;&nu; &mu;&epsilon;&lambda;ώ&nu; &tau;&eta;&sigmaf; &alpha;&pi;&omicron;&tau;&epsilon;&lambda;&omicron;ύ&nu; &mu;&iota;&alpha; &alpha;&kappa;ό&mu;&alpha; &pi;&eta;&gamma;ή &epsilon;&sigma;ό&delta;&omega;&nu;. &Tau;έ&lambda;&omicron;&sigmaf;, &mu;έ&chi;&rho;&iota; &kappa;&alpha;&iota; &tau;&omicron; 2009, &epsilon;&pi;&iota;&chi;&omicron;&rho;&eta;&gamma;&omicron;ύ&nu;&tau;&alpha;&nu; &alpha;&pi;ό &tau;&eta;&nu; &Gamma;.&Gamma;.&Pi;.&Pi;.</p>
<p>&nbsp;</p>
<p><strong>15. Έ&chi;&omega; &delta;&epsilon;&iota; ό&tau;&iota; &delta;&rho;&alpha;&sigma;&tau;&eta;&rho;&iota;&omicron;&pi;&omicron;&iota;&omicron;ύ&nu;&tau;&alpha;&iota; &kappa;&alpha;&iota; ά&lambda;&lambda;&epsilon;&sigmaf; &omicron;&mu;ά&delta;&epsilon;&sigmaf; &sigma;&tau;&omicron; &chi;ώ&rho;&omicron; &tau;&eta;&sigmaf; &Pi;&omicron;&lambda;&iota;&tau;&iota;&kappa;ή&sigmaf; &Pi;&rho;&omicron;&sigma;&tau;&alpha;&sigma;ί&alpha;&sigmaf; &mu;&epsilon; &delta;&omega;&rho;&epsilon;ά&nu; &epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;&eta;. &Gamma;&iota;&alpha;&tau;ί &nu;&alpha; &epsilon;&pi;&iota;&lambda;έ&xi;&omega; &tau;&eta;&nu; &Epsilon;.&Omicron;.&Delta;.;</strong></p>
<p>&Eta; &Epsilon;.&Omicron;.&Delta;. έ&chi;&epsilon;&iota; &alpha;&pi;&omicron;&delta;&epsilon;ί&xi;&epsilon;&iota; &gamma;&iota;&alpha; 3 &delta;&epsilon;&kappa;&alpha;&epsilon;&tau;ί&epsilon;&sigmaf; &tau;ώ&rho;&alpha; ό&tau;&iota; &eta; &delta;έ&sigma;&mu;&epsilon;&upsilon;&sigma;&eta; &sigma;&tau;&omicron; &sigma;&tau;ό&chi;&omicron; &kappa;&alpha;&iota; &eta; &alpha;&pi;&omicron;&tau;&epsilon;&lambda;&epsilon;&sigma;&mu;&alpha;&tau;&iota;&kappa;ό&tau;&eta;&tau;ά &tau;&eta;&sigmaf;, &epsilon;ί&nu;&alpha;&iota; 2 &alpha;&pi;ό &tau;&alpha; &chi;&alpha;&rho;&alpha;&kappa;&tau;&eta;&rho;&iota;&sigma;&tau;&iota;&kappa;ά &pi;&omicron;&upsilon; &tau;&eta;&nu; &omicron;&delta;ή&gamma;&eta;&sigma;&alpha;&nu; &sigma;&tau;&omicron; &nu;&alpha; &epsilon;ί&nu;&alpha;&iota; &eta; &mu;&epsilon;&gamma;&alpha;&lambda;ύ&tau;&epsilon;&rho;&eta; &kappa;&alpha;&iota; &alpha;&pi;&omicron;&tau;&epsilon;&lambda;&epsilon;&sigma;&mu;&alpha;&tau;&iota;&kappa;ό&tau;&epsilon;&rho;&eta; &Mu;.&Kappa;.&Omicron;., &epsilon;&theta;&epsilon;&lambda;&omicron;&nu;&tau;&iota;&kappa;ή &omicron;&rho;&gamma;ά&nu;&omega;&sigma;&eta; &sigma;&tau;&eta;&nu; &Epsilon;&lambda;&lambda;ά&delta;&alpha;. Έ&chi;&epsilon;&iota; &epsilon;&iota;&delta;&iota;&kappa;ό &kappa;&alpha;&theta;&epsilon;&sigma;&tau;ώ&sigmaf; &sigma;&upsilon;&nu;&epsilon;&rho;&gamma;&alpha;&sigma;ί&alpha;&sigmaf; &mu;&epsilon; &tau;&eta;&nu; &Pi;&omicron;&lambda;&epsilon;&mu;&iota;&kappa;ή &Alpha;&epsilon;&rho;&omicron;&pi;&omicron;&rho;ί&alpha;, &tau;&omicron; &Pi;&omicron;&lambda;&epsilon;&mu;&iota;&kappa;ό &Nu;&alpha;&upsilon;&tau;&iota;&kappa;ό &kappa;&alpha;&iota; &tau;&omicron; &Lambda;&iota;&mu;&epsilon;&nu;&iota;&kappa;ό &Sigma;ώ&mu;&alpha; &epsilon;&nu;ώ &epsilon;ί&nu;&alpha;&iota; &pi;&lambda;ή&rho;&epsilon;&sigmaf; &mu;έ&lambda;&omicron;&sigmaf; &sigma;&tau;&omicron;&upsilon;&sigmaf; &mu;&epsilon;&gamma;&alpha;&lambda;ύ&tau;&epsilon;&rho;&omicron;&upsilon;&sigmaf; &delta;&iota;&epsilon;&theta;&nu;&epsilon;ί&sigmaf; &omicron;&rho;&gamma;&alpha;&nu;&iota;&sigma;&mu;&omicron;ύ&sigmaf; &pi;&iota;&sigma;&tau;&omicron;&pi;&omicron;ί&eta;&sigma;&eta;&sigmaf; &alpha;&nu;ά &epsilon;&iota;&delta;&iota;&kappa;ό&tau;&eta;&tau;&alpha;, &pi;&rho;&omicron;&sigma;&phi;έ&rho;&omicron;&nu;&tau;&alpha;&sigmaf; έ&tau;&sigma;&iota; &sigma;&tau;&alpha; &mu;έ&lambda;&eta; &tau;&eta;&sigmaf; &tau;&omicron; &alpha;&rho;&tau;&iota;ό&tau;&epsilon;&rho;&omicron; &delta;&upsilon;&nu;&alpha;&tau;ό &epsilon;&pi;ί&pi;&epsilon;&delta;&omicron; &tau;&epsilon;&chi;&nu;&omicron;&gamma;&nu;&omega;&sigma;ί&alpha;&sigmaf;.</p>
<p>&Sigma;&tau;&eta;&nu; &Epsilon;.&Omicron;.&Delta;. &pi;&rho;&omega;&tau;&alpha;&rho;&chi;&iota;&kappa;ό&sigmaf; &sigma;&tau;ό&chi;&omicron;&sigmaf; &mu;&alpha;&sigmaf; &epsilon;ί&nu;&alpha;&iota; &nu;&alpha; &epsilon;&kappa;&pi;&alpha;&iota;&delta;&epsilon;&upsilon;ό&mu;&alpha;&sigma;&tau;&epsilon; &sigma;&omega;&sigma;&tau;ά &kappa;&alpha;&iota; &alpha;&nu; &kappa;&alpha;&iota; &epsilon;&theta;&epsilon;&lambda;&omicron;&nu;&tau;έ&sigmaf; &nu;&alpha; &epsilon;&nu;&epsilon;&rho;&gamma;&omicron;ύ&mu;&epsilon; &mu;&epsilon; &epsilon;&pi;&alpha;&gamma;&gamma;&epsilon;&lambda;&mu;&alpha;&tau;&iota;&kappa;ή &epsilon;&upsilon;&sigma;&upsilon;&nu;&epsilon;&iota;&delta;&eta;&sigma;ί&alpha;.</p>
<p>&nbsp;</p>
<p><strong>16. &Epsilon;ί&mu;&alpha;&iota; &epsilon;&theta;&epsilon;&lambda;&omicron;&nu;&tau;ή&sigmaf;. &Gamma;&iota;&alpha;&tau;ί &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &pi;&lambda;&eta;&rho;ώ&sigma;&omega; &gamma;&iota;&alpha; &tau;&eta;&nu; &epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;&eta; &mu;&omicron;&upsilon;;</strong></p>
<p>&Eta; &epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;&eta; &tau;&eta;&sigmaf; &Epsilon;.&Omicron;.&Delta;. &delta;&epsilon;&nu; &epsilon;ί&nu;&alpha;&iota; &delta;&omega;&rho;&epsilon;ά&nu; &kappa;&alpha;&iota; &alpha;&upsilon;&tau;ό &gamma;&iota;&alpha; &delta;ύ&omicron; &kappa;&upsilon;&rho;ί&omega;&sigmaf; &lambda;ό&gamma;&omicron;&upsilon;&sigmaf;:</p>
<p><strong>&alpha;)</strong>&nbsp;Ό&tau;&alpha;&nu; &sigma;&tau;&omicron; &pi;&alpha;&rho;&epsilon;&lambda;&theta;ό&nu; &delta;ό&theta;&eta;&kappa;&epsilon; &delta;&omega;&rho;&epsilon;ά&nu; &eta; &epsilon;&xi;&epsilon;&iota;&delta;&iota;&kappa;&epsilon;&upsilon;&mu;έ&nu;&eta; &gamma;&nu;ώ&sigma;&eta;, &delta;&epsilon;&nu; &epsilon;&kappa;&tau;&iota;&mu;ή&theta;&eta;&kappa;&epsilon; &delta;&epsilon;ό&nu;&tau;&omega;&sigmaf; &alpha;&pi;ό &mu;&epsilon;&gamma;ά&lambda;&omicron; &mu;έ&rho;&omicron;&sigmaf; &tau;&omega;&nu; &upsilon;&pi;&omicron;&psi;&eta;&phi;ί&omega;&nu;, &pi;&rho;&omicron;&sigma;&beta;ά&lambda;&lambda;&omicron;&nu;&tau;&alpha;&sigmaf; έ&tau;&sigma;&iota; ό&lambda;&omicron;&upsilon;&sigmaf; ό&sigma;&omicron;&upsilon;&sigmaf; &gamma;&iota;&alpha; &pi;&omicron;&lambda;&lambda;ά &chi;&rho;ό&nu;&iota;&alpha; &epsilon;&rho;&gamma;ά&sigma;&tau;&eta;&kappa;&alpha;&nu;, ί&delta;&rho;&omega;&sigma;&alpha;&nu; &kappa;&alpha;&iota; &mu;ό&chi;&theta;&eta;&sigma;&alpha;&nu; &gamma;&iota;&alpha; &tau;&omicron; &sigma;&kappa;&omicron;&pi;ό &alpha;&upsilon;&tau;ό.</p>
<p><strong>&beta;)&nbsp;</strong>&Alpha;&pi;ό &tau;&alpha; έ&sigma;&omicron;&delta;&alpha; &tau;&eta;&sigmaf; &sigma;&chi;&omicron;&lambda;ή&sigmaf; &beta;&alpha;&sigma;&iota;&kappa;ή&sigmaf; &epsilon;&kappa;&pi;&alpha;ί&delta;&epsilon;&upsilon;&sigma;&eta;&sigmaf;, &sigma;&upsilon;&nu;&tau;&eta;&rho;&epsilon;ί&tau;&alpha;&iota; &mu;έ&rho;&omicron;&sigmaf; &tau;&eta;&sigmaf; &gamma;&rho;&alpha;&mu;&mu;&alpha;&tau;&epsilon;ί&alpha;&sigmaf; &tau;&eta;&sigmaf; &omicron;&rho;&gamma;ά&nu;&omega;&sigma;&eta;&sigmaf; &eta; &omicron;&pi;&omicron;ί&alpha; &epsilon;ί&nu;&alpha;&iota; &alpha;&pi;&alpha;&rho;&alpha;ί&tau;&eta;&tau;&eta; &gamma;&iota;&alpha; &tau;&eta; &delta;&iota;&epsilon;&kappa;&pi;&epsilon;&rho;&alpha;ί&omega;&sigma;&eta; &pi;&omicron;&lambda;&lambda;ώ&nu; &epsilon;&rho;&gamma;&alpha;&sigma;&iota;ώ&nu; &sigma;&epsilon; &kappa;&alpha;&theta;&eta;&mu;&epsilon;&rho;&iota;&nu;ή &beta;ά&sigma;&eta;.</p>
</td>
</tr>
</tbody>
</table> <br><br><br>

<?php include 'footer.php'; ?>

</body>
</html>